In [1]:
import numpy as np
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [2]:
data_1 = ['apple', 'apple', 'mango', 'apple', 'banana', 'banana', 'mango', 'apple']
values_of_seq = np.array(data_1)
print(values_of_seq)

['apple' 'apple' 'mango' 'apple' 'banana' 'banana' 'mango' 'apple']


In [3]:
# label encoding
label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values_of_seq)
print(integer_encoded)

[0 0 2 0 1 1 2 0]


In [4]:
#ohe
onehot_encoder = OneHotEncoder(sparse_output=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

[[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
