In [1]:
import numpy as np

X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float)
y = np.array(([92], [86], [89]), dtype=float)

In [2]:
# Normalizing and scaling respectively
X = X/np.amax(X, axis=0) #maximum of X array longitudinally
y = y/100

In [3]:
X, y

(array([[0.66666667, 1.        ],
        [0.33333333, 0.55555556],
        [1.        , 0.66666667]]),
 array([[0.92],
        [0.86],
        [0.89]]))

In [4]:
#Sigmoid Function
def sigmoid (x):
    return 1/(1 + np.exp(-x))

#Derivative of Sigmoid Function
def derivatives_sigmoid(x):
    return sigmoid(x) * (1 - sigmoid(x))

In [5]:
epoch=5
lr=0.1

In [6]:
inp_l_neurons = 2
hidd_l_neurons = 3
op_l_neurons = 1

wh=np.random.uniform(size=(inp_l_neurons,hidd_l_neurons))
bh=np.random.uniform(size=(1,hidd_l_neurons))
wout=np.random.uniform(size=(hidd_l_neurons,op_l_neurons))
bout=np.random.uniform(size=(1,op_l_neurons))

#draws a random range of numbers uniformly of dim x*y
for i in range(epoch):
    #Forward Propogation
    h_inp_i=np.dot(X,wh)
    h_inp=h_inp_i + bh
    hlayer_op = sigmoid(h_inp)
    
    outinp_i=np.dot(hlayer_op,wout)
    outinp= outinp_i+bout
    output = sigmoid(outinp)

   # Backpropagation
    EO = y - output
    d_output = EO * derivatives_sigmoid(output)
    d_hiddenlayer = (d_output.dot(wout.T)) * derivatives_sigmoid(hlayer_op)

    wout += hlayer_op.T.dot(d_output) *lr   # dotproduct of nextlayererror and currentlayerop
    wh += X.T.dot(d_hiddenlayer) *lr

    print ("-----------Epoch-", i+1, "Starts----------")
    print("Input: \n" + str(X))
    print("Actual Output: \n" + str(y))
    print("Predicted Output: \n" ,output)
    print ("-----------Epoch-", i+1, "Ends----------\n")

print("Input: \n" + str(X))
print("Actual Output: \n" + str(y))
print("Predicted Output: \n" ,output)

-----------Epoch- 1 Starts----------
Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.83843984]
 [0.81311535]
 [0.83713594]]
-----------Epoch- 1 Ends----------

-----------Epoch- 2 Starts----------
Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.83940312]
 [0.81405987]
 [0.83809848]]
-----------Epoch- 2 Ends----------

-----------Epoch- 3 Starts----------
Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.84034693]
 [0.81498605]
 [0.8390416 ]]
-----------Epoch- 3 Ends----------

-----------Epoch- 4 Starts----------
Input: 
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
Actual Output: 
[[0.92]
 [0.86]
 [0.89]]
Predicted Output: 
 [[0.84127177]
 [0.81589437]
 [0.839