In [2]:
import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def tanh(x):
    return np.tanh(x)

def relu(x):
    return np.maximum(0, x)

def leaky_relu(x, alpha=0.01):
    return np.maximum(alpha * x, x)

def softmax(x):
    exp_x = np.exp(x)
    return exp_x / np.sum(exp_x)


In [3]:
x = np.array([-1, 0, 1])

# Sigmoid
print(sigmoid(x))

# Tanh
print(tanh(x))

# ReLU
print(relu(x))

# Leaky ReLU
print(leaky_relu(x))

# Softmax
print(softmax(x))

[0.26894142 0.5        0.73105858]
[-0.76159416  0.          0.76159416]
[0 0 1]
[-0.01  0.    1.  ]
[0.09003057 0.24472847 0.66524096]
